/**
 * 离线演示数据 —— 与 docs/04 §8 的规范算例完全一致。
 *
 * 用途：后端未启动时前端仍可渲染（设计评审 / 视觉走查）。
 * **屏幕上会显示「离线演示数据」横幅**，绝不让人误以为这是真实结果。
 */

import type {
  Evidence,
  EventsFixture,
  OpportunityCard,
  OpportunityDetail,
  RadarPayload,
  ScoreBreakdown,
} from './types'

export const FIXTURE_EVIDENCE: Evidence[] = [
  {
    id: 1001,
    source_type: 'announcement',
    source_name: '巨潮资讯',
    source_url: 'http://static.cninfo.com.cn/example.pdf',
    publication_time: '2026-09-08T11:32:00Z',
    reliability_level: 'A',
    reliability_note: '公司正式公告 / 交易所披露',
    assertion_kind: 'fact',
    document_id: 'ANN-2026-0908-001',
    relevant_text: '公司控股股东拟以协议转让方式向 XX 集团转让其所持全部股份',
    page: 2,
    para_index: 7,
    extracted_facts: ['控股股东拟转让全部股份', '受让方为 XX 集团'],
    confidence: 0.96,
    freshness: 'stale',
    relative_time: '3天前',
  },
  {
    id: 1004,
    source_type: 'announcement',
    source_name: '巨潮资讯',
    source_url: 'http://static.cninfo.com.cn/example2.pdf',
    publication_time: '2026-09-08T11:32:00Z',
    reliability_level: 'A',
    reliability_note: '公司正式公告 / 交易所披露',
    assertion_kind: 'fact',
    document_id: 'ANN-2026-0908-002',
    relevant_text: '公司拟以发行股份方式购买 XX 新能源科技有限公司 100% 股权',
    page: 1,
    para_index: 4,
    extracted_facts: ['拟发行股份购买资产', '标的为 XX 新能源'],
    confidence: 0.94,
  },
]

export const FIXTURE_CARD: OpportunityCard = {
  id: 301,
  company: { id: 88, name: 'ST XXX', code: '600xxx', industry: '机械设备', is_st: true },
  thesis_type: 'restructuring',
  thesis_display_name: '重组预期',
  status: 'pending_confirmation',
  status_label: '待确认',
  match_score: 94,
  rule_score: 67.5875,
  risk_score: 40.75,
  semantic_score: 76,
  divergence: 8.41,
  divergence_flagged: false,
  why_in_radar: [
    '发布重大资产重组预案公告',
    '控股股东近期发生变化',
    '存在潜在资产注入迹象',
    '公司处于 ST 状态且连续亏损',
  ],
  summary:
    '该标的高度符合你的重组预期策略。但目前仍处于方案确认阶段，核心资产及交易对价尚未完全明确。',
  latest_events: [
    {
      id: 501,
      event_type: 'RESTRUCTURING',
      event_type_label: '重大资产重组',
      title: '重大资产重组预案公告',
      summary: '公司披露重组预案，交易标的与对价尚未确定。',
      event_time: '2026-09-08T11:32:00Z',
      discovery_time: '2026-09-08T11:35:12Z',
      importance: 0.91,
      certainty: 0.88,
      certainty_level: 'disclosed',
      source_type: 'announcement',
      source_url: 'http://static.cninfo.com.cn/example.pdf',
      affected_thesis: ['restructuring'],
      evidence_ids: [1001],
      is_invalidating: false,
      freshness: 'stale',
      relative_time: '3天前',
    },
    {
      id: 502,
      event_type: 'CONTROL_CHANGE',
      event_type_label: '控制权变更',
      title: '关于控股股东变更的公告',
      event_time: '2026-09-06T09:10:00Z',
      importance: 0.86,
      certainty: 0.9,
      certainty_level: 'disclosed',
      source_type: 'announcement',
      affected_thesis: ['restructuring'],
      evidence_ids: [1001],
      is_invalidating: false,
      freshness: 'stale',
      relative_time: '5天前',
    },
  ],
  ai_judgement:
    '该标的高度符合你的重组预期策略。但目前仍处于方案确认阶段，核心资产及交易对价尚未完全明确。',
  evidence_count: 2,
  contradictory_count: 2,
  open_question_count: 6,
  risk_count: 2,
  a_grade_evidence_count: 2,
  only_market_discussion: false,
  next_events_to_watch: ['重组方案公告', '交易所问询回复', '资产评估结果', '股东大会', '监管审核'],
  risks: ['重组存在失败可能', '公司基本面较弱'],
  score_version: 'rules-1.0+weights-restructuring-1.0',
  first_discovered_at: '2026-09-08T19:40:00Z',
  last_updated_at: '2026-09-11T07:20:00Z',
}

export const FIXTURE_BREAKDOWN: ScoreBreakdown = {
  rule_score: 67.5875,
  semantic_score: 76,
  divergence: 8.41,
  divergence_flagged: false,
  risk_score: 40.75,
  score_version: 'rules-1.0+weights-restructuring-1.0',
  computed_at: '2026-09-11T07:20:00Z',
  dimensions: [
    {
      dimension: 'thesis_match',
      display_name: '逻辑匹配',
      raw_value: 94,
      weight: 0.3,
      weighted_value: 28.2,
      direction: 'positive',
      items: [
        {
          rule_id: 'R-RE-TM-01',
          delta: 94,
          reason: '策略权重比 1.00 × 核心条件覆盖 0.94（94%）',
          evidence_ids: [1001, 1004],
        },
      ],
    },
    {
      dimension: 'event_catalyst',
      display_name: '事件催化',
      raw_value: 90,
      weight: 0.25,
      weighted_value: 22.5,
      direction: 'positive',
      items: [
        { rule_id: 'R-GEN-EV-01', delta: 40, reason: '存在 A 类公告直接对应核心事件类型', evidence_ids: [1001] },
        { rule_id: 'R-GEN-EV-02', delta: 25, reason: '同期出现 3 个不同事件类型（组合催化）', evidence_ids: [1001, 1004] },
        { rule_id: 'R-GEN-EV-03', delta: 15, reason: '事件涉及金额达显著阈值（最高占比 0.20）', evidence_ids: [1004] },
        { rule_id: 'R-GEN-EV-04', delta: 10, reason: '事件牵涉可识别的产业方 / 头部企业', evidence_ids: [1001] },
      ],
    },
    {
      dimension: 'catalyst_strength',
      display_name: '催化剂强度',
      raw_value: 40,
      weight: 0.1,
      weighted_value: 4,
      direction: 'positive',
      items: [
        { rule_id: 'R-RE-CS-01', delta: 40, reason: '预案披露｜重组预案、发行股份购买资产预案', evidence_ids: [] },
      ],
    },
    {
      dimension: 'certainty',
      display_name: '确定性',
      raw_value: 45,
      weight: 0.1,
      weighted_value: 4.5,
      direction: 'positive',
      items: [
        { rule_id: 'R-GEN-CT-00', delta: 100, reason: '确定性基线：最高证据等级 A（公司正式公告 / 交易所披露）', evidence_ids: [] },
        { rule_id: 'R-GEN-CT-01', delta: -30, reason: '存在 6 项待确认事项（8/项，上限 30）', evidence_ids: [] },
        { rule_id: 'R-GEN-CT-02', delta: -15, reason: '存在未回复的监管问询 / 问询函', evidence_ids: [] },
        { rule_id: 'R-GEN-CT-04', delta: -10, reason: '公司历史上有同类事项失败记录', evidence_ids: [] },
      ],
    },
    {
      dimension: 'fundamentals',
      display_name: '基本面',
      raw_value: 50,
      weight: 0.05,
      weighted_value: 2.5,
      direction: 'positive',
      items: [{ rule_id: 'R-GEN-FD-00', delta: 50, reason: '基本面基线', evidence_ids: [] }],
    },
    {
      dimension: 'shareholder_structure',
      display_name: '股东结构变化',
      raw_value: 90,
      weight: 0.1,
      weighted_value: 9,
      direction: 'positive',
      items: [
        { rule_id: 'R-GEN-SH-00', delta: 50, reason: '股东结构基线', evidence_ids: [] },
        { rule_id: 'R-GEN-SH-01', delta: 40, reason: '控股股东 / 实际控制人发生变更', evidence_ids: [1001] },
      ],
    },
    {
      dimension: 'market_attention',
      display_name: '市场关注',
      raw_value: 60,
      weight: 0.05,
      weighted_value: 3,
      direction: 'positive',
      items: [
        { rule_id: 'R-GEN-MA-00', delta: 40, reason: '市场关注基线', evidence_ids: [] },
        { rule_id: 'R-GEN-MA-02', delta: 15, reason: '出现股票异常波动公告', evidence_ids: [] },
        { rule_id: 'R-GEN-MA-05', delta: 5, reason: '存在 E 类社交媒体热议（仅在此维度计分）', evidence_ids: [] },
      ],
    },
    {
      dimension: 'history_case',
      display_name: '历史相似案例',
      raw_value: 0,
      weight: 0,
      weighted_value: 0,
      direction: 'positive',
      items: [{ rule_id: 'R-GEN-HC-00', delta: 0, reason: '历史案例库未启用（Phase 2）', evidence_ids: [] }],
    },
    {
      dimension: 'risk',
      display_name: '风险',
      raw_value: 40.75,
      weight: -0.15,
      weighted_value: -6.1125,
      direction: 'negative',
      direction_note: '★ 数值越高代表风险越大（与上方维度方向相反）',
      items: [
        { rule_id: 'R-GEN-RK-EVENT_FAILURE', delta: 0.55, reason: '事件失败可能性：中（0.55）｜公司历史上有同类事项失败记录', evidence_ids: [] },
        { rule_id: 'R-GEN-RK-REGULATORY', delta: 0.45, reason: '监管 / 合规风险：中（0.45）｜存在未回复的监管问询', evidence_ids: [] },
        { rule_id: 'R-GEN-RK-FUNDAMENTALS_DETERIORATION', delta: 0.4, reason: '公司基本面恶化：中（0.40）', evidence_ids: [] },
        { rule_id: 'R-GEN-RK-PLEDGE', delta: 0.2, reason: '大股东质押 / 资金占用：中低（0.20）', evidence_ids: [] },
        { rule_id: 'R-GEN-RK-TRADABILITY', delta: 0.2, reason: '可交易性：中低（0.20）', evidence_ids: [] },
      ],
    },
  ],
  disclaimer:
    '评分为概率性研究线索的相对排序信号，不构成投资建议，不代表任何收益预期。系统只辅助发现、解释、验证与跟踪，不替用户决策。',
}

export const FIXTURE_DETAIL: OpportunityDetail = {
  card: FIXTURE_CARD,
  thesis: {
    id: 12,
    thesis_type: 'restructuring',
    display_name: '重组预期',
    statement: '公司处于 ST 状态，同时出现重大资产重组及控制权变化，因此存在潜在重组预期。',
    why_now: {
      past: '公司长期处于 ST 状态、连续 2 年亏损',
      recent: '近期出现重大资产重组、控制权变化',
      this_week: '最新事件：重大资产重组预案公告',
      conclusion: '因此该公司进入「重组预期」机会池。',
    },
    supporting_evidence: FIXTURE_EVIDENCE,
    contradictory_evidence: [
      {
        id: 1005,
        source_type: 'announcement',
        source_name: '巨潮资讯',
        source_url: 'http://static.cninfo.com.cn/example3.pdf',
        publication_time: '2024-11-02T10:00:00Z',
        reliability_level: 'A',
        reliability_note: '公司正式公告 / 交易所披露',
        assertion_kind: 'fact',
        relevant_text: '公司决定终止筹划本次重大资产重组事项',
        page: 1,
        para_index: 3,
        extracted_facts: ['2024 年曾终止重组'],
        confidence: 0.93,
      },
    ],
    invalidating_events: [
      { event_type: 'RESTRUCTURING', severity: 'terminal', description: '重组终止 / 重大资产重组失败' },
      { event_type: 'CONTROL_CHANGE', severity: 'severe', description: '控股权变更取消' },
      { event_type: 'REGULATORY_RISK', severity: 'terminal', description: '监管否决' },
      { event_type: 'ASSET_INJECTION', severity: 'severe', description: '核心资产退出' },
      { event_type: 'LITIGATION', severity: 'severe', description: '重大诉讼致交易基础受损' },
    ],
  },
  open_questions: [
    { id: 1, question: '交易标的', status: 'open' },
    { id: 2, question: '交易价格', status: 'open' },
    { id: 3, question: '重组方案', status: 'open' },
    { id: 4, question: '资产评估结果', status: 'open' },
    { id: 5, question: '监管审核结果', status: 'open' },
    { id: 6, question: '股东大会决议', status: 'open' },
    { id: 7, question: '重大资产重组预案公告', status: 'confirmed', confirmed_evidence_id: 1001 },
  ],
  confirmed_facts: ['出现重大资产重组相关公告（A 类）', '存在控制权 / 实际控制人变化', '存在资产注入或资产置换迹象', '经营困境背景'],
  risks: [
    { factor: '重组存在失败可能', weight: null, severity: null, description: '公司历史上有终止记录，方案尚未确定' },
    { factor: '公司基本面较弱', weight: null, severity: null, description: '连续亏损，净资产承压' },
  ],
  next_events_to_watch: ['重组方案公告', '交易所问询回复', '资产评估结果', '股东大会', '监管审核'],
  timeline: [
    { date: '2026-09-02', event_type: 'REGULATORY_RISK', title: '股票异常波动公告', evidence_id: null },
    { date: '2026-09-06', event_type: 'CONTROL_CHANGE', title: '控股股东变更', evidence_id: 1001 },
    { date: '2026-09-08', event_type: 'RESTRUCTURING', title: '重大资产重组预案公告', evidence_id: 1001 },
  ],
  evidence: FIXTURE_EVIDENCE,
  news_clusters: [],
  market: { note: '行情数据仅作辅助信息，用于观察事件后的价格行为（规格 §46）' },
  status_history: [
    { from_status: null, to_status: 'discovered', reason: '进入重组预期候选池', score_before: null, score_after: null, changed_at: '2026-09-08T19:40:00Z' },
    { from_status: 'discovered', to_status: 'pending_confirmation', reason: '存在 6 项待确认事项', score_before: null, score_after: 67.59, changed_at: '2026-09-08T20:05:00Z' },
  ],
  disclaimer:
    '评分为概率性研究线索的相对排序信号，不构成投资建议，不代表任何收益预期。系统只辅助发现、解释、验证与跟踪，不替用户决策。',
}

export const FIXTURE_RADAR: RadarPayload = {
  profile: {
    id: 1,
    name: '默认画像（重组猎手模板）',
    top_weights: [
      { thesis_type: 'restructuring', display_name: '重组预期', weight: 0.4 },
      { thesis_type: 'ma_integration', display_name: '并购 / 产业整合', weight: 0.25 },
      { thesis_type: 'turnaround', display_name: '困境反转', weight: 0.15 },
      { thesis_type: 'shareholder_action', display_name: '股东行为', weight: 0.1 },
      { thesis_type: 'event_driven', display_name: '事件驱动', weight: 0.1 },
    ],
    auto_learn_enabled: true,
    locked_weights: ['restructuring'],
  },
  today: {
    date: '2026-09-11',
    is_trading_day: true,
    calendar_degraded: true,
    calendar_warning: '⚠ 交易日历不可用，已退化为「工作日 = 交易日」。法定节假日将空跑一次调度。',
    new_count: 12,
    cards: [FIXTURE_CARD],
  },
  counts: {
    discovered: 5,
    pending_confirmation: 12,
    tracking: 8,
    thesis_confirmed: 3,
    observing: 2,
    invalidated: 2,
    archived: 1,
  },
  recent_events: [
    { ...FIXTURE_CARD.latest_events[0], company: FIXTURE_CARD.company },
    { ...FIXTURE_CARD.latest_events[1], company: FIXTURE_CARD.company },
  ],
  alerts: [
    {
      id: 7,
      alert_type: 'thesis_invalidated',
      title: '投资逻辑发生重大变化',
      message: '某公司：你关注的重组预期逻辑出现失效事件 —— 重大资产重组终止',
      suggestion: '建议重新评估该机会',
      opportunity_id: 301,
      score_before: 94,
      score_after: 31,
      is_read: false,
      created_at: '2026-09-11T07:20:00Z',
      relative_time: '2小时前',
    },
  ],
  pipeline: {
    last_run_at: '2026-09-11T00:32:00Z',
    dry_run: true,
    funnel: {
      candidates: 301,
      announcements_fetched: 74,
      announcements_skipped: 23,
      passed_prefilter: 51,
      events_extracted: 43,
      thesis_candidates: 19,
      deep_analyzed: 8,
      cards: 6,
    },
    quality: {
      parse_failure_rate: 0.04,
      llm_schema_failure_rate: 0.06,
      evidence_rejected: 3,
    },
    hint: 'passed_prefilter → events_extracted',
  },
  disclaimer:
    '评分为概率性研究线索的相对排序信号，不构成投资建议，不代表任何收益预期。系统只辅助发现、解释、验证与跟踪，不替用户决策。',
}

/** 事件流演示数据 */
export const FIXTURE_EVENTS: EventsFixture = {
  data: [
    { ...FIXTURE_CARD.latest_events[0], company: FIXTURE_CARD.company },
    { ...FIXTURE_CARD.latest_events[1], company: FIXTURE_CARD.company },
  ],
  page: { limit: 50, offset: 0, total: 2, has_more: false },
}

/** My Thesis 演示数据 */
export const FIXTURE_MY_THESIS = {
  total_tracking: 12,
  by_type: [
    { display_name: '重组预期', count: 5 },
    { display_name: '困境反转', count: 4 },
    { display_name: '事件驱动', count: 3 },
  ],
  items: [
    {
      id: 12,
      opportunity_id: 301,
      company: FIXTURE_CARD.company,
      thesis_type: 'restructuring' as const,
      display_name: '重组预期',
      statement: '公司处于 ST 状态，同时出现重大资产重组及控制权变化，因此存在潜在重组预期。',
      status: 'pending_confirmation' as const,
      rule_score: 67.59,
      risk_score: 40.75,
      evidence_count: 2,
      contradictory_count: 1,
      open_question_count: 6,
      invalidating_events: ['重组终止 / 重大资产重组失败', '控股权变更取消', '监管否决', '核心资产退出'],
      next_events_to_watch: ['重组方案公告', '交易所问询回复', '资产评估结果'],
      last_updated_at: '2026-09-11T07:20:00Z',
      has_unread_alert: true,
    },
  ],
  disclaimer: FIXTURE_BREAKDOWN.disclaimer,
}
