"""add why_in_radar to opportunity

Revision ID: dedafb592c95
Revises: 14d07fc5e6a7
Create Date: 2026-09-11 13:09:18.565025

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


revision: str = 'dedafb592c95'
down_revision: str | None = '14d07fc5e6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('why_in_radar', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_column('why_in_radar')

    # ### end Alembic commands ###
