"""add catalyst_stage and accept_early_signals

Revision ID: 47845a70b30d
Revises: dedafb592c95
Create Date: 2026-09-12 18:35:46.534246

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


revision: str = '47845a70b30d'
down_revision: str | None = 'dedafb592c95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: SQLite 无法给**已有数据**的表添加 NOT NULL 列而不给默认值
    # （会报 "Cannot add a NOT NULL column with default value NULL"）。
    # 因此这里显式给出 server_default —— 新列的语义也与之一致：
    #   accept_early_signals 默认 True（宁可见到并标注，也不要静默漏掉）
    #   catalyst_stage 默认空串（表示尚未计算）
    #   is_early_signal 默认 False
    with op.batch_alter_table('investmentprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accept_early_signals', sa.Boolean(),
                                      nullable=False, server_default=sa.text('1')))

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalyst_stage', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('is_early_signal', sa.Boolean(),
                                      nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_opportunity_catalyst_stage'), ['catalyst_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_is_early_signal'), ['is_early_signal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_is_early_signal'))
        batch_op.drop_index(batch_op.f('ix_opportunity_catalyst_stage'))
        batch_op.drop_column('is_early_signal')
        batch_op.drop_column('catalyst_stage')

    with op.batch_alter_table('investmentprofile', schema=None) as batch_op:
        batch_op.drop_column('accept_early_signals')

    # ### end Alembic commands ###
