"""initial schema

Revision ID: 14d07fc5e6a7
Revises: 
Create Date: 2026-09-11 12:27:09.178919

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


revision: str = '14d07fc5e6a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unified_social_credit_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry_chain', sa.JSON(), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('controlling_shareholder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actual_controller', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_risk_warning', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_is_risk_warning'), ['is_risk_warning'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_is_st'), ['is_st'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_unified_social_credit_code'), ['unified_social_credit_code'], unique=False)

    op.create_table('ingestrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('parse_failed', sa.Integer(), nullable=False),
    sa.Column('parse_needs_ocr', sa.Integer(), nullable=False),
    sa.Column('parse_failure_rate', sa.Float(), nullable=True),
    sa.Column('field_missing_rate', sa.Float(), nullable=True),
    sa.Column('funnel', sa.JSON(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('error_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestrun_started_at'), ['started_at'], unique=False)

    op.create_table('investor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investor_handle'), ['handle'], unique=True)

    op.create_table('llmnoderun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'CACHED', 'SCHEMA_ERROR', 'LLM_ERROR', 'BANNED_WORD', name='noderunstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('raw_output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'input_hash', 'prompt_version', name='uq_llm_cache_key')
    )
    with op.batch_alter_table('llmnoderun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llmnoderun_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llmnoderun_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_llmnoderun_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llmnoderun_node_name'), ['node_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_llmnoderun_prompt_version'), ['prompt_version'], unique=False)

    op.create_table('thesisinvalidationrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_type', sa.Enum('RESTRUCTURING', 'TURNAROUND', 'VALUE', 'GROWTH', 'EVENT_DRIVEN', 'POLICY', 'CYCLE', 'PRODUCT', 'SHAREHOLDER_ACTION', 'MA_INTEGRATION', name='thesistype'), nullable=False),
    sa.Column('event_type', sa.Enum('M_AND_A', 'RESTRUCTURING', 'ASSET_INJECTION', 'CONTROL_CHANGE', 'SHAREHOLDER_BUY', 'SHAREHOLDER_SELL', 'BUYBACK', 'BANKRUPTCY_REORGANIZATION', 'EARNINGS_TURNAROUND', 'POLICY_CATALYST', 'MAJOR_CONTRACT', 'NEW_PRODUCT', 'MANAGEMENT_CHANGE', 'REGULATORY_RISK', 'LITIGATION', 'DIVIDEND_POLICY', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('match_condition', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('TERMINAL', 'SEVERE', 'WARNING', name='invalidationseverity'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_type', 'event_type', 'severity', name='uq_invalidation_rule')
    )
    with op.batch_alter_table('thesisinvalidationrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesisinvalidationrule_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesisinvalidationrule_thesis_type'), ['thesis_type'], unique=False)

    op.create_table('thesistypedef',
    sa.Column('code', sa.Enum('RESTRUCTURING', 'TURNAROUND', 'VALUE', 'GROWTH', 'EVENT_DRIVEN', 'POLICY', 'CYCLE', 'PRODUCT', 'SHAREHOLDER_ACTION', 'MA_INTEGRATION', name='thesistype'), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('IMPLEMENTED', 'DESIGNED', 'PLANNED', name='strategystatus'), nullable=False),
    sa.Column('user_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('core_conditions', sa.JSON(), nullable=True),
    sa.Column('rule_spec', sa.JSON(), nullable=True),
    sa.Column('thesis_statement_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_event_types', sa.JSON(), nullable=True),
    sa.Column('invalidating_event_types', sa.JSON(), nullable=True),
    sa.Column('open_question_templates', sa.JSON(), nullable=True),
    sa.Column('catalyst_ladder', sa.JSON(), nullable=True),
    sa.Column('default_weights', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('evidence_requirements', sa.JSON(), nullable=True),
    sa.Column('anti_patterns', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('announcement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sa.Enum('M_AND_A', 'RESTRUCTURING', 'ASSET_INJECTION', 'CONTROL_CHANGE', 'SHAREHOLDER_BUY', 'SHAREHOLDER_SELL', 'BUYBACK', 'BANKRUPTCY_REORGANIZATION', 'EARNINGS_TURNAROUND', 'POLICY_CATALYST', 'MAJOR_CONTRACT', 'NEW_PRODUCT', 'MANAGEMENT_CHANGE', 'REGULATORY_RISK', 'LITIGATION', 'DIVIDEND_POLICY', 'OTHER', name='eventtype'), nullable=True),
    sa.Column('publication_time', sa.DateTime(), nullable=False),
    sa.Column('discovery_time', sa.DateTime(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fulltext', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parse_status', sa.Enum('OK', 'PARTIAL', 'FAILED', 'NEEDS_OCR', name='parsestatus'), nullable=False),
    sa.Column('parse_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=False),
    sa.Column('ingest_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingestrun.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_id', name='uq_announcement_doc')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_discovery_time'), ['discovery_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_parse_status'), ['parse_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_publication_time'), ['publication_time'], unique=False)

    op.create_table('eventcluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sa.Enum('M_AND_A', 'RESTRUCTURING', 'ASSET_INJECTION', 'CONTROL_CHANGE', 'SHAREHOLDER_BUY', 'SHAREHOLDER_SELL', 'BUYBACK', 'BANKRUPTCY_REORGANIZATION', 'EARNINGS_TURNAROUND', 'POLICY_CATALYST', 'MAJOR_CONTRACT', 'NEW_PRODUCT', 'MANAGEMENT_CHANGE', 'REGULATORY_RISK', 'LITIGATION', 'DIVIDEND_POLICY', 'OTHER', name='eventtype'), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventcluster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventcluster_company_id'), ['company_id'], unique=False)

    op.create_table('financialperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'report_type', name='uq_fin_period')
    )
    with op.batch_alter_table('financialperiod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financialperiod_company_id'), ['company_id'], unique=False)

    op.create_table('investmentprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('horizon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('markets', sa.JSON(), nullable=True),
    sa.Column('industry_prefs', sa.JSON(), nullable=True),
    sa.Column('exclusions', sa.JSON(), nullable=True),
    sa.Column('risk_tolerance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_learn_enabled', sa.Boolean(), nullable=False),
    sa.Column('locked_weights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investmentprofile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investmentprofile_investor_id'), ['investor_id'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_company_id'), ['company_id'], unique=False)

    op.create_table('thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('thesis_type', sa.Enum('RESTRUCTURING', 'TURNAROUND', 'VALUE', 'GROWTH', 'EVENT_DRIVEN', 'POLICY', 'CYCLE', 'PRODUCT', 'SHAREHOLDER_ACTION', 'MA_INTEGRATION', name='thesistype'), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('why_now_past', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('why_now_recent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('why_now_this_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('why_now_conclusion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('contradictory_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('invalidating_event_types', sa.JSON(), nullable=True),
    sa.Column('open_question_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesis_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesis_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesis_thesis_type'), ['thesis_type'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('M_AND_A', 'RESTRUCTURING', 'ASSET_INJECTION', 'CONTROL_CHANGE', 'SHAREHOLDER_BUY', 'SHAREHOLDER_SELL', 'BUYBACK', 'BANKRUPTCY_REORGANIZATION', 'EARNINGS_TURNAROUND', 'POLICY_CATALYST', 'MAJOR_CONTRACT', 'NEW_PRODUCT', 'MANAGEMENT_CHANGE', 'REGULATORY_RISK', 'LITIGATION', 'DIVIDEND_POLICY', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('discovery_time', sa.DateTime(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('certainty', sa.Float(), nullable=False),
    sa.Column('certainty_level', sa.Enum('DISCLOSED', 'PARTIALLY_DISCLOSED', 'MEDIA_REPORTED', 'MARKET_RUMOR', name='certaintylevel'), nullable=False),
    sa.Column('source_type', sa.Enum('ANNOUNCEMENT', 'FINANCIAL_REPORT', 'NEWS', 'POLICY', 'PRICE', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affected_thesis', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_invalidating', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['eventcluster.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'event_type', 'event_time', 'source_url', name='uq_event_dedup')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_discovery_time'), ['discovery_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_is_invalidating'), ['is_invalidating'], unique=False)

    op.create_table('financialmetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('yoy', sa.Float(), nullable=True),
    sa.Column('qoq', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['financialperiod.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'metric', name='uq_fin_metric')
    )
    with op.batch_alter_table('financialmetric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financialmetric_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_financialmetric_period_id'), ['period_id'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_reliability', sa.Enum('A', 'B', 'C', 'D', 'E', name='reliabilitylevel'), nullable=False),
    sa.Column('publication_time', sa.DateTime(), nullable=False),
    sa.Column('discovery_time', sa.DateTime(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_company_ids', sa.JSON(), nullable=True),
    sa.Column('related_industries', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.Enum('M_AND_A', 'RESTRUCTURING', 'ASSET_INJECTION', 'CONTROL_CHANGE', 'SHAREHOLDER_BUY', 'SHAREHOLDER_SELL', 'BUYBACK', 'BANKRUPTCY_REORGANIZATION', 'EARNINGS_TURNAROUND', 'POLICY_CATALYST', 'MAJOR_CONTRACT', 'NEW_PRODUCT', 'MANAGEMENT_CHANGE', 'REGULATORY_RISK', 'LITIGATION', 'DIVIDEND_POLICY', 'OTHER', name='eventtype'), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['eventcluster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_news_source')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_publication_time'), ['publication_time'], unique=False)

    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'PENDING_CONFIRMATION', 'TRACKING', 'THESIS_CONFIRMED', 'OBSERVING', 'INVALIDATED', 'ARCHIVED', name='opportunitystatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('divergence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('why_now', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('contradictory_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('uncertainties', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('next_events_to_watch', sa.JSON(), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('score_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['investmentprofile.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'profile_id', 'thesis_id', name='uq_opportunity_triple')
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_first_discovered_at'), ['first_discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_match_score'), ['match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_rule_score'), ['rule_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_thesis_id'), ['thesis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_user_id'), ['user_id'], unique=False)

    op.create_table('paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('para_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'page', 'para_index', name='uq_paragraph_loc')
    )
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paragraph_announcement_id'), ['announcement_id'], unique=False)

    op.create_table('profilethesisweight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('thesis_type', sa.Enum('RESTRUCTURING', 'TURNAROUND', 'VALUE', 'GROWTH', 'EVENT_DRIVEN', 'POLICY', 'CYCLE', 'PRODUCT', 'SHAREHOLDER_ACTION', 'MA_INTEGRATION', name='thesistype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['investmentprofile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'thesis_type', name='uq_profile_thesis_weight')
    )
    with op.batch_alter_table('profilethesisweight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profilethesisweight_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profilethesisweight_thesis_type'), ['thesis_type'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score_before', sa.Float(), nullable=True),
    sa.Column('score_after', sa.Float(), nullable=True),
    sa.Column('triggered_by_event_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ANNOUNCEMENT', 'FINANCIAL_REPORT', 'NEWS', 'POLICY', 'PRICE', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_time', sa.DateTime(), nullable=False),
    sa.Column('reliability_level', sa.Enum('A', 'B', 'C', 'D', 'E', name='reliabilitylevel'), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relevant_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('para_index', sa.Integer(), nullable=True),
    sa.Column('assertion_kind', sa.Enum('FACT', 'INFERENCE', 'HYPOTHESIS', 'MARKET_DISCUSSION', name='assertionkind'), nullable=False),
    sa.Column('extracted_facts', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('produced_by_node_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ),
    sa.ForeignKeyConstraint(['produced_by_node_run_id'], ['llmnoderun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_announcement_id'), ['announcement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_publication_time'), ['publication_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_reliability_level'), ['reliability_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_type'), ['source_type'], unique=False)

    op.create_table('opportunityscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('THESIS_MATCH', 'EVENT_CATALYST', 'CATALYST_STRENGTH', 'CERTAINTY', 'FUNDAMENTALS', 'SHAREHOLDER_STRUCTURE', 'MARKET_ATTENTION', 'HISTORY_CASE', 'RISK', name='scoredimension'), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weighted_value', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('RULE', 'LLM', name='scoresource'), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'dimension', 'source', name='uq_score_dim')
    )
    with op.batch_alter_table('opportunityscore', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunityscore_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunityscore_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('opportunitystatuslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DISCOVERED', 'PENDING_CONFIRMATION', 'TRACKING', 'THESIS_CONFIRMED', 'OBSERVING', 'INVALIDATED', 'ARCHIVED', name='opportunitystatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DISCOVERED', 'PENDING_CONFIRMATION', 'TRACKING', 'THESIS_CONFIRMED', 'OBSERVING', 'INVALIDATED', 'ARCHIVED', name='opportunitystatus'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_by_event_id', sa.Integer(), nullable=True),
    sa.Column('score_before', sa.Float(), nullable=True),
    sa.Column('score_after', sa.Float(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunitystatuslog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunitystatuslog_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('scoreitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('RULE', 'LLM', name='scoresource'), nullable=False),
    sa.Column('dimension', sa.Enum('THESIS_MATCH', 'EVENT_CATALYST', 'CATALYST_STRENGTH', 'CERTAINTY', 'FUNDAMENTALS', 'SHAREHOLDER_STRUCTURE', 'MARKET_ATTENTION', 'HISTORY_CASE', 'RISK', name='scoredimension'), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoreitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoreitem_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoreitem_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('useraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_thesis_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useraction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_useraction_investor_id'), ['investor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_useraction_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('watchlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['investmentprofile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'opportunity_id', name='uq_watchlist_item')
    )
    with op.batch_alter_table('watchlistitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlistitem_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlistitem_profile_id'), ['profile_id'], unique=False)

    op.create_table('openquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed_evidence_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openquestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openquestion_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openquestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openquestion_opportunity_id'))

    op.drop_table('openquestion')
    with op.batch_alter_table('watchlistitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlistitem_profile_id'))
        batch_op.drop_index(batch_op.f('ix_watchlistitem_opportunity_id'))

    op.drop_table('watchlistitem')
    with op.batch_alter_table('useraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useraction_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_useraction_investor_id'))
        batch_op.drop_index(batch_op.f('ix_useraction_created_at'))

    op.drop_table('useraction')
    with op.batch_alter_table('scoreitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoreitem_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_scoreitem_dimension'))

    op.drop_table('scoreitem')
    with op.batch_alter_table('opportunitystatuslog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunitystatuslog_opportunity_id'))

    op.drop_table('opportunitystatuslog')
    with op.batch_alter_table('opportunityscore', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunityscore_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunityscore_dimension'))

    op.drop_table('opportunityscore')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_source_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_reliability_level'))
        batch_op.drop_index(batch_op.f('ix_evidence_publication_time'))
        batch_op.drop_index(batch_op.f('ix_evidence_announcement_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_alert_is_read'))
        batch_op.drop_index(batch_op.f('ix_alert_created_at'))

    op.drop_table('alert')
    with op.batch_alter_table('profilethesisweight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profilethesisweight_thesis_type'))
        batch_op.drop_index(batch_op.f('ix_profilethesisweight_profile_id'))

    op.drop_table('profilethesisweight')
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paragraph_announcement_id'))

    op.drop_table('paragraph')
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_user_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_thesis_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_status'))
        batch_op.drop_index(batch_op.f('ix_opportunity_rule_score'))
        batch_op.drop_index(batch_op.f('ix_opportunity_profile_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_match_score'))
        batch_op.drop_index(batch_op.f('ix_opportunity_first_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_opportunity_company_id'))

    op.drop_table('opportunity')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_publication_time'))
        batch_op.drop_index(batch_op.f('ix_news_external_id'))
        batch_op.drop_index(batch_op.f('ix_news_cluster_id'))

    op.drop_table('news')
    with op.batch_alter_table('financialmetric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financialmetric_period_id'))
        batch_op.drop_index(batch_op.f('ix_financialmetric_metric'))

    op.drop_table('financialmetric')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_is_invalidating'))
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_event_time'))
        batch_op.drop_index(batch_op.f('ix_event_discovery_time'))
        batch_op.drop_index(batch_op.f('ix_event_company_id'))
        batch_op.drop_index(batch_op.f('ix_event_cluster_id'))

    op.drop_table('event')
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesis_thesis_type'))
        batch_op.drop_index(batch_op.f('ix_thesis_is_active'))
        batch_op.drop_index(batch_op.f('ix_thesis_company_id'))

    op.drop_table('thesis')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_company_id'))
        batch_op.drop_index(batch_op.f('ix_stock_code'))

    op.drop_table('stock')
    with op.batch_alter_table('investmentprofile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investmentprofile_investor_id'))

    op.drop_table('investmentprofile')
    with op.batch_alter_table('financialperiod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financialperiod_company_id'))

    op.drop_table('financialperiod')
    with op.batch_alter_table('eventcluster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventcluster_company_id'))

    op.drop_table('eventcluster')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_publication_time'))
        batch_op.drop_index(batch_op.f('ix_announcement_parse_status'))
        batch_op.drop_index(batch_op.f('ix_announcement_event_type'))
        batch_op.drop_index(batch_op.f('ix_announcement_document_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_discovery_time'))
        batch_op.drop_index(batch_op.f('ix_announcement_company_id'))

    op.drop_table('announcement')
    op.drop_table('thesistypedef')
    with op.batch_alter_table('thesisinvalidationrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesisinvalidationrule_thesis_type'))
        batch_op.drop_index(batch_op.f('ix_thesisinvalidationrule_event_type'))

    op.drop_table('thesisinvalidationrule')
    with op.batch_alter_table('llmnoderun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llmnoderun_prompt_version'))
        batch_op.drop_index(batch_op.f('ix_llmnoderun_node_name'))
        batch_op.drop_index(batch_op.f('ix_llmnoderun_model'))
        batch_op.drop_index(batch_op.f('ix_llmnoderun_input_hash'))
        batch_op.drop_index(batch_op.f('ix_llmnoderun_created_at'))

    op.drop_table('llmnoderun')
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investor_handle'))

    op.drop_table('investor')
    with op.batch_alter_table('ingestrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestrun_started_at'))

    op.drop_table('ingestrun')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_unified_social_credit_code'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_is_st'))
        batch_op.drop_index(batch_op.f('ix_company_is_risk_warning'))
        batch_op.drop_index(batch_op.f('ix_company_industry'))

    op.drop_table('company')
    # ### end Alembic commands ###
